spring:
  redis:
    host: 43.143.231.137
    port: 6379
    password: Aa20341103
    database: 14
    lettuce:
      pool:
        max-active: 8
        max-wait: 100ms
        min-idle: 0
        max-idle: 8


